[package]
name = "ffs"
version = "0.1.0"
authors = ["Michael Greenberg <michael.greenberg@pomona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
clap = "2.0"
fuser = "0.8"
libc = "0.2.51"
serde_json = "1.0"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2.18"
yaml-rust = "0.4.5"
